# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='taggit.proto',
  package='taggit_pb',
  serialized_pb='\n\x0ctaggit.proto\x12\ttaggit_pb\" \n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1f\n\x03Tag\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"*\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t*\x08\x08\x64\x10\x80\x80\x80\x80\x02\"\x94\x01\n\x05Paper\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x0f\n\x07lastmod\x18\x05 \x01(\t\x12\x0e\n\x06\x62ibtex\x18\x06 \x01(\t20\n\x05paper\x12\x0f.taggit_pb.Item\x18\x65 \x01(\x0b\x32\x10.taggit_pb.Paper\"?\n\x0bUserTagItem\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0e\n\x06tag_id\x18\x02 \x01(\x05\x12\x0f\n\x07item_id\x18\x03 \x01(\x05\"\xfd\x01\n\x06VLists\x12\x1e\n\x05users\x18\x01 \x03(\x0b\x32\x0f.taggit_pb.User\x12\x1c\n\x04tags\x18\x02 \x03(\x0b\x32\x0e.taggit_pb.Tag\x12\x1e\n\x05items\x18\x03 \x03(\x0b\x32\x0f.taggit_pb.Item\x12$\n\x04utis\x18\x04 \x03(\x0b\x32\x16.taggit_pb.UserTagItem\x12 \n\x06papers\x18\x05 \x03(\x0b\x32\x10.taggit_pb.Paper\x12\r\n\x05query\x18\x0b \x01(\t\x12\x17\n\x0cquery_offset\x18\x0c \x01(\x05:\x01\x30\x12\x15\n\nquery_size\x18\r \x01(\x05:\x01\x30\x12\x0e\n\x06status\x18\x65 \x01(\t\"/\n\x0bJsonRequest\x12 \n\x05input\x18\x01 \x01(\x0b\x32\x11.taggit_pb.VLists\"1\n\x0cJsonResponse\x12!\n\x06output\x18\x01 \x01(\x0b\x32\x11.taggit_pb.VLists')




_USER = descriptor.Descriptor(
  name='User',
  full_name='taggit_pb.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='taggit_pb.User.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='taggit_pb.User.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=59,
)


_TAG = descriptor.Descriptor(
  name='Tag',
  full_name='taggit_pb.Tag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='taggit_pb.Tag.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='taggit_pb.Tag.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=61,
  serialized_end=92,
)


_ITEM = descriptor.Descriptor(
  name='Item',
  full_name='taggit_pb.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='taggit_pb.Item.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='taggit_pb.Item.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 536870912), ],
  serialized_start=94,
  serialized_end=136,
)


_PAPER = descriptor.Descriptor(
  name='Paper',
  full_name='taggit_pb.Paper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='title', full_name='taggit_pb.Paper.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='author', full_name='taggit_pb.Paper.author', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='year', full_name='taggit_pb.Paper.year', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='url', full_name='taggit_pb.Paper.url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lastmod', full_name='taggit_pb.Paper.lastmod', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bibtex', full_name='taggit_pb.Paper.bibtex', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='paper', full_name='taggit_pb.Paper.paper', index=0,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=139,
  serialized_end=287,
)


_USERTAGITEM = descriptor.Descriptor(
  name='UserTagItem',
  full_name='taggit_pb.UserTagItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='taggit_pb.UserTagItem.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tag_id', full_name='taggit_pb.UserTagItem.tag_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='item_id', full_name='taggit_pb.UserTagItem.item_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=289,
  serialized_end=352,
)


_VLISTS = descriptor.Descriptor(
  name='VLists',
  full_name='taggit_pb.VLists',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='users', full_name='taggit_pb.VLists.users', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tags', full_name='taggit_pb.VLists.tags', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='items', full_name='taggit_pb.VLists.items', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='utis', full_name='taggit_pb.VLists.utis', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='papers', full_name='taggit_pb.VLists.papers', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='query', full_name='taggit_pb.VLists.query', index=5,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='query_offset', full_name='taggit_pb.VLists.query_offset', index=6,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='query_size', full_name='taggit_pb.VLists.query_size', index=7,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='taggit_pb.VLists.status', index=8,
      number=101, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=355,
  serialized_end=608,
)


_JSONREQUEST = descriptor.Descriptor(
  name='JsonRequest',
  full_name='taggit_pb.JsonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='input', full_name='taggit_pb.JsonRequest.input', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=610,
  serialized_end=657,
)


_JSONRESPONSE = descriptor.Descriptor(
  name='JsonResponse',
  full_name='taggit_pb.JsonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='output', full_name='taggit_pb.JsonResponse.output', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=659,
  serialized_end=708,
)

_VLISTS.fields_by_name['users'].message_type = _USER
_VLISTS.fields_by_name['tags'].message_type = _TAG
_VLISTS.fields_by_name['items'].message_type = _ITEM
_VLISTS.fields_by_name['utis'].message_type = _USERTAGITEM
_VLISTS.fields_by_name['papers'].message_type = _PAPER
_JSONREQUEST.fields_by_name['input'].message_type = _VLISTS
_JSONRESPONSE.fields_by_name['output'].message_type = _VLISTS
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Tag'] = _TAG
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['Paper'] = _PAPER
DESCRIPTOR.message_types_by_name['UserTagItem'] = _USERTAGITEM
DESCRIPTOR.message_types_by_name['VLists'] = _VLISTS
DESCRIPTOR.message_types_by_name['JsonRequest'] = _JSONREQUEST
DESCRIPTOR.message_types_by_name['JsonResponse'] = _JSONRESPONSE

class User(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USER
  
  # @@protoc_insertion_point(class_scope:taggit_pb.User)

class Tag(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TAG
  
  # @@protoc_insertion_point(class_scope:taggit_pb.Tag)

class Item(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ITEM
  
  # @@protoc_insertion_point(class_scope:taggit_pb.Item)

class Paper(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PAPER
  
  # @@protoc_insertion_point(class_scope:taggit_pb.Paper)

class UserTagItem(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERTAGITEM
  
  # @@protoc_insertion_point(class_scope:taggit_pb.UserTagItem)

class VLists(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VLISTS
  
  # @@protoc_insertion_point(class_scope:taggit_pb.VLists)

class JsonRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _JSONREQUEST
  
  # @@protoc_insertion_point(class_scope:taggit_pb.JsonRequest)

class JsonResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _JSONRESPONSE
  
  # @@protoc_insertion_point(class_scope:taggit_pb.JsonResponse)

_PAPER.extensions_by_name['paper'].message_type = _PAPER
Item.RegisterExtension(_PAPER.extensions_by_name['paper'])
# @@protoc_insertion_point(module_scope)
